### ISSUE TITLE
What is recommended flex report ? 

### ISSUE THREAD

**Issue by uMag** [titov-vv/ledger#1]
What fields and parts must be in minimal IBKR flex report, to be able to generate stats and russian tax form ?

**Comment by titov-vv** [comment]
There are no minimal set - application will use only data available in the database. Thus you simply will have shorter tax report if some data would be missing in flex.
I recommend not to include "extra" sections due to [ibflex](https://github.com/csingley/ibflex) limitations - Cristopher have this kind of recommendations:
_You can configure whatever you like and ibflex should parse it, with these exceptions:
        You can't use European-style date formats (dd/MM/yy or dd/MM/yyyy). Just accept the default (yyyyMMdd) or get with the program and use ISO-8601 (yyyy-MM-dd).
        You should use some delimiter between dates & times. The default delimiter (semicolon) is fastest to process.
        For the Trades section of the statement, you can't select the options at the top for "Symbol Summary", "Asset Class", or "Orders". These will blow up the parser. It's fine to check the box for "Asset Class" down below, along with the other selections for XML attributes._

As you may see some sections may explode.
I was able to verify and test with following set of data:
- Account information (this is essential to match report with account number)
- Cash report
- Cash transactions
- Comission details
- Corporate actions (not really in use for the moment)
- Financial instument information (good to have for automaic addion of securities)
- Interest Accruals 
- Interest Details (this part isn't fully tested)
- Trades
- Transaction fees
- Transfers
